"""initial_migration

Revision ID: 302a9cd06c05
Revises: 
Create Date: 2026-02-09 10:00:41.904140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '302a9cd06c05'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('objetive', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emergency_contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emergency_contact_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('archived_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_archived_at'), 'clients', ['archived_at'], unique=False)
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=False)
    op.create_index(op.f('ix_clients_full_name'), 'clients', ['full_name'], unique=False)
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('muscles', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)
    op.create_index(op.f('ix_exercises_is_active'), 'exercises', ['is_active'], unique=False)
    op.create_index(op.f('ix_exercises_muscles'), 'exercises', ['muscles'], unique=False)
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=False)
    op.create_table('pack_types',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sessions_total', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pack_types_is_active'), 'pack_types', ['is_active'], unique=False)
    op.create_index(op.f('ix_pack_types_name'), 'pack_types', ['name'], unique=False)
    op.create_table('training_plans',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_plans_end_date'), 'training_plans', ['end_date'], unique=False)
    op.create_index(op.f('ix_training_plans_id'), 'training_plans', ['id'], unique=False)
    op.create_index(op.f('ix_training_plans_name'), 'training_plans', ['name'], unique=False)
    op.create_index(op.f('ix_training_plans_start_date'), 'training_plans', ['start_date'], unique=False)
    op.create_index(op.f('ix_training_plans_status'), 'training_plans', ['status'], unique=False)
    op.create_table('client_active_plans',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('training_plan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active_from', sa.Date(), nullable=False),
    sa.Column('active_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['training_plan_id'], ['training_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_active_plans_active_from'), 'client_active_plans', ['active_from'], unique=False)
    op.create_index(op.f('ix_client_active_plans_active_to'), 'client_active_plans', ['active_to'], unique=False)
    op.create_index(op.f('ix_client_active_plans_client_id'), 'client_active_plans', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_active_plans_id'), 'client_active_plans', ['id'], unique=False)
    op.create_index(op.f('ix_client_active_plans_training_plan_id'), 'client_active_plans', ['training_plan_id'], unique=False)
    op.create_table('client_packs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pack_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('purchase_at', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('sessions_total_snapshot', sa.Integer(), nullable=False),
    sa.Column('sessions_used', sa.Integer(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('next_pack_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('renewal_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cancelled_at', sa.Date(), nullable=True),
    sa.Column('archived_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['next_pack_type_id'], ['pack_types.id'], ),
    sa.ForeignKeyConstraint(['pack_type_id'], ['pack_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_packs_archived_at'), 'client_packs', ['archived_at'], unique=False)
    op.create_index(op.f('ix_client_packs_cancelled_at'), 'client_packs', ['cancelled_at'], unique=False)
    op.create_index(op.f('ix_client_packs_purchase_at'), 'client_packs', ['purchase_at'], unique=False)
    op.create_index(op.f('ix_client_packs_renewal_status'), 'client_packs', ['renewal_status'], unique=False)
    op.create_index(op.f('ix_client_packs_valid_until'), 'client_packs', ['valid_until'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('starts_at', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_client_id'), 'sessions', ['client_id'], unique=False)
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_starts_at'), 'sessions', ['starts_at'], unique=False)
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_table('training_plan_days',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_plan_days_id'), 'training_plan_days', ['id'], unique=False)
    op.create_index(op.f('ix_training_plan_days_order_index'), 'training_plan_days', ['order_index'], unique=False)
    op.create_index(op.f('ix_training_plan_days_plan_id'), 'training_plan_days', ['plan_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel', sa.Enum('WHATSAPP', 'EMAIL', name='notificationchannel'), nullable=False),
    sa.Column('recipient_type', sa.Enum('CLIENT', 'TRAINER', name='recipienttype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'CANCELLED', name='notificationstatus'), nullable=False),
    sa.Column('recipient', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_channel'), 'notifications', ['channel'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_type'), 'notifications', ['recipient_type'], unique=False)
    op.create_index(op.f('ix_notifications_scheduled_for'), 'notifications', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_notifications_session_id'), 'notifications', ['session_id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_table('pack_consumptions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_pack_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['client_pack_id'], ['client_packs.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pack_consumptions_client_pack_id'), 'pack_consumptions', ['client_pack_id'], unique=False)
    op.create_index(op.f('ix_pack_consumptions_id'), 'pack_consumptions', ['id'], unique=False)
    op.create_index(op.f('ix_pack_consumptions_session_id'), 'pack_consumptions', ['session_id'], unique=False)
    op.create_table('plan_day_exercises',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan_day_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exercise_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps_range', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('rest_range_seconds', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('tempo', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('is_superset', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('substitution_allowed', sa.Boolean(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['plan_day_id'], ['training_plan_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_day_exercises_exercise_id'), 'plan_day_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_plan_day_exercises_id'), 'plan_day_exercises', ['id'], unique=False)
    op.create_index(op.f('ix_plan_day_exercises_plan_day_id'), 'plan_day_exercises', ['plan_day_id'], unique=False)
    op.create_table('plan_exercise_set_loads',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan_day_exercise_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('load_kg', sa.Float(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['plan_day_exercise_id'], ['plan_day_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_exercise_set_loads_id'), 'plan_exercise_set_loads', ['id'], unique=False)
    op.create_index(op.f('ix_plan_exercise_set_loads_plan_day_exercise_id'), 'plan_exercise_set_loads', ['plan_day_exercise_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_exercise_set_loads_plan_day_exercise_id'), table_name='plan_exercise_set_loads')
    op.drop_index(op.f('ix_plan_exercise_set_loads_id'), table_name='plan_exercise_set_loads')
    op.drop_table('plan_exercise_set_loads')
    op.drop_index(op.f('ix_plan_day_exercises_plan_day_id'), table_name='plan_day_exercises')
    op.drop_index(op.f('ix_plan_day_exercises_id'), table_name='plan_day_exercises')
    op.drop_index(op.f('ix_plan_day_exercises_exercise_id'), table_name='plan_day_exercises')
    op.drop_table('plan_day_exercises')
    op.drop_index(op.f('ix_pack_consumptions_session_id'), table_name='pack_consumptions')
    op.drop_index(op.f('ix_pack_consumptions_id'), table_name='pack_consumptions')
    op.drop_index(op.f('ix_pack_consumptions_client_pack_id'), table_name='pack_consumptions')
    op.drop_table('pack_consumptions')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_session_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_scheduled_for'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_channel'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_training_plan_days_plan_id'), table_name='training_plan_days')
    op.drop_index(op.f('ix_training_plan_days_order_index'), table_name='training_plan_days')
    op.drop_index(op.f('ix_training_plan_days_id'), table_name='training_plan_days')
    op.drop_table('training_plan_days')
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_starts_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_client_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_client_packs_valid_until'), table_name='client_packs')
    op.drop_index(op.f('ix_client_packs_renewal_status'), table_name='client_packs')
    op.drop_index(op.f('ix_client_packs_purchase_at'), table_name='client_packs')
    op.drop_index(op.f('ix_client_packs_cancelled_at'), table_name='client_packs')
    op.drop_index(op.f('ix_client_packs_archived_at'), table_name='client_packs')
    op.drop_table('client_packs')
    op.drop_index(op.f('ix_client_active_plans_training_plan_id'), table_name='client_active_plans')
    op.drop_index(op.f('ix_client_active_plans_id'), table_name='client_active_plans')
    op.drop_index(op.f('ix_client_active_plans_client_id'), table_name='client_active_plans')
    op.drop_index(op.f('ix_client_active_plans_active_to'), table_name='client_active_plans')
    op.drop_index(op.f('ix_client_active_plans_active_from'), table_name='client_active_plans')
    op.drop_table('client_active_plans')
    op.drop_index(op.f('ix_training_plans_status'), table_name='training_plans')
    op.drop_index(op.f('ix_training_plans_start_date'), table_name='training_plans')
    op.drop_index(op.f('ix_training_plans_name'), table_name='training_plans')
    op.drop_index(op.f('ix_training_plans_id'), table_name='training_plans')
    op.drop_index(op.f('ix_training_plans_end_date'), table_name='training_plans')
    op.drop_table('training_plans')
    op.drop_index(op.f('ix_pack_types_name'), table_name='pack_types')
    op.drop_index(op.f('ix_pack_types_is_active'), table_name='pack_types')
    op.drop_table('pack_types')
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_muscles'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_is_active'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.drop_index(op.f('ix_clients_full_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_index(op.f('ix_clients_archived_at'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
